version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=web
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5431:5432

volumes:
  postgres: {}